### ISSUE TITLE
Add CircleCI or GitHub Actions

### ISSUE THREAD

**Issue by craicoverflow** [craicoverflow/sailr#12]

**Comment by neelkamath** [comment]
I'll do it.

**Comment by neelkamath** [comment]
This issue is labeled as "hacktoberfest", but is ineligible for it:

<img width="1440" alt="Screen Shot 2020-10-04 at 10 59 40 AM" src="https://user-images.githubusercontent.com/24778804/95007748-cd731400-0630-11eb-9051-14a6c1b3fd3e.png">

This is either because you need to re-add the hacktoberfest label (perhaps because you added it before October), or you need to add the hacktoberfest topic to your repo's topics temporarily.
